System:
  Cpu: 30
  Memory: 10
  ChannelCount: 350000
  FilterCount: 30
Kafka:
  Topic: 'yanshi.topic'
  Broker: '192.168.30.61:19091,192.168.30.61:19092,192.168.30.61:19093'
  threads: 24
  Version: '0.10.2.1'
  ClientId: 'go-client'
  GroupId: 'go-dat22a32252d445512113'
  FromBeginning: False
Filter:
  match:
    - 'srcAddress regex ^10\. & destPort in 3306,9200'
  Convert:
    - 'eventId'
    - 'eventNum'
Clickhouse:
  Database: 'ailpha'
  TableName: 'ailpha_securitylog_test'
  Fields: '*'
  Debug: False
  UserName: 'default'
  Password: ''
  BlockSize: 300000
  Hosts: '192.168.30.190:19100'
  FlushSize: 200000
  FlushTime: 30
  Lz4Compress: 1
  Concurrent: 8
  Location: 'Asia/Shanghai'
  ConnectionLifeTime: 60
  DateTimeFormat:
    - '2006-01-02 15:04:05'
    - '2006-01-02T15:04:05Z'